"""create recommendation metrics table

Revision ID: 92e64ef07b99
Revises: b958e656d6e7
Create Date: 2026-07-26 12:04:04.856717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e64ef07b99'
down_revision: Union[str, Sequence[str], None] = 'b958e656d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('precision_at_k', sa.Float(), nullable=False),
    sa.Column('recall_at_k', sa.Float(), nullable=False),
    sa.Column('ndcg_at_k', sa.Float(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_metrics_id'), 'recommendation_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_metrics_user_id'), 'recommendation_metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_metrics_user_id'), table_name='recommendation_metrics')
    op.drop_index(op.f('ix_recommendation_metrics_id'), table_name='recommendation_metrics')
    op.drop_table('recommendation_metrics')
    # ### end Alembic commands ###
