"""create user exclusions table

Revision ID: b958e656d6e7
Revises: 719f82e5b0a6
Create Date: 2026-07-24 20:26:25.271569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b958e656d6e7'
down_revision: Union[str, Sequence[str], None] = '719f82e5b0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_user_category_exclusion')
    )
    op.create_index(op.f('ix_user_exclusions_category'), 'user_exclusions', ['category'], unique=False)
    op.create_index(op.f('ix_user_exclusions_id'), 'user_exclusions', ['id'], unique=False)
    op.create_index(op.f('ix_user_exclusions_user_id'), 'user_exclusions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_exclusions_user_id'), table_name='user_exclusions')
    op.drop_index(op.f('ix_user_exclusions_id'), table_name='user_exclusions')
    op.drop_index(op.f('ix_user_exclusions_category'), table_name='user_exclusions')
    op.drop_table('user_exclusions')
    # ### end Alembic commands ###
